apiVersion: apps/v1
kind: Deployment
metadata:
  name: hongjot-dev-deployment
  namespace: hongjot-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: summer-workshop-hongjot
          image: ghcr.io/secretlabrat/hongjot:5359ebe50ee206f56030f3b5e0b023e392c88f42
          imagePullPolicy: Always
          env:
              -  name: SERVER_PORT
                 valueFrom:
                     configMapKeyRef:
                         name: app-config
                         key: server.port
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
                cpu: "0.25"
                memory: 128Mi